import "./App.css";
import MovieCard from "./components/MovieCard";
function App() {
  let temp = {
    title: "this is title",
    release_date: "1999-99-99",
    url: "",
  };
  return (
    <div>
      {/* <Text />
      <Text prop="my content" /> */}
      <MovieCard Movie={temp} />
    </div>
  );
}

function Text({ prop = "default value" }) {
  return (
    <div>
      {/* <p>Content generated by Test()</p> */}
      <p>prop content is {prop}</p>
    </div>
  );
}
export default App;
